### ISSUE TITLE
How to add coupon code feature in addon packages 

### ISSUE THREAD

**Issue by Sun121232** [strangerstudios/pmpro-addon-packages#52]

**Comment by MaryOJob** [comment]
Moderators Only: #504883

Member wants to be able to apply a discount code to an add-on package page or post.

**Comment by kimcoleman** [comment]
With PMPro v3.0+, members can now hold multiple membership levels. We suggest instead of using this Add On, to instead set up a level group that allows multiple selections. This will allow you to use core PMPro's discount code features. This Addon is not encouraged for use and rather use core levels in the correct way with v3.0+.
